export const FETCHEDDATA = "FETCHED_DATA";
export const FETCHINGDATA = "FETCHING_DATA";
export const FETCHINGDATAFAIL = "FETHING_DATA_FAIL";
export const ADDINGDATA = "ADDING_DATA";
export const DELETINGDATA = "DELETING_DATA";
